/**
 * ``sponsio scan`` — re-mine contracts from code, write/append to yaml.
 *
 * Mirrors the Python ``sponsio scan`` library-maintenance flow: AST
 * scan a path, infer deterministic contracts heuristically, write a
 * sponsio.yaml (or append to an existing one). Used *after* ``onboard``
 * has set up the project — when you've added new tools and want to
 * refresh the contract list.
 *
 * Differs from the default ``npx sponsio <patterns>`` mode (which
 * emits a tools.json inventory) and from ``onboard`` (first-time
 * setup, prints integration patch + framework detection). This is
 * the maintenance command, silent except for the yaml output.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import * as yaml from "js-yaml";
import { scan as runAstScan } from "./index";
import { suggestDetNlContracts, buildFallbackPayload } from "./onboard";

const HELP =
  "sponsio scan — AST-scan source for tools, write contracts to sponsio.yaml\n" +
  "\n" +
  "USAGE:\n" +
  "  sponsio scan <patterns...> [options]\n" +
  "\n" +
  "ARGUMENTS:\n" +
  "  <patterns...>     Glob(s) or directories to scan (default: src/**/*.{ts,tsx,js,jsx})\n" +
  "\n" +
  "OPTIONS:\n" +
  "  -a, --agent <id>      Agent id stamped into yaml (default: agent)\n" +
  "  -o, --out <file>      Output yaml path (default: sponsio.yaml; '-' = stdout)\n" +
  "      --append          Merge into existing yaml's contracts list (deduped)\n" +
  "      --mode <m>        runtime.mode if creating a new yaml (default: observe)\n" +
  "  -h, --help            Show this help\n" +
  "\n" +
  "EXAMPLES:\n" +
  "  sponsio scan ./src\n" +
  "  sponsio scan 'src/tools/**/*.ts' -o sponsio.yaml\n" +
  "  sponsio scan ./src --append\n" +
  "  sponsio scan ./src -o -                   # print to stdout\n";

interface ScanOptions {
  patterns: string[];
  agent: string;
  out: string;
  append: boolean;
  mode: "observe" | "enforce";
}

function parseArgs(argv: string[]): ScanOptions {
  const opts: ScanOptions = {
    patterns: [],
    agent: "agent",
    out: "sponsio.yaml",
    append: false,
    mode: "observe",
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "-h" || a === "--help") {
      process.stdout.write(HELP);
      process.exit(0);
    }
    if (a === "-a" || a === "--agent") {
      opts.agent = argv[++i];
      continue;
    }
    if (a === "-o" || a === "--out") {
      opts.out = argv[++i];
      continue;
    }
    if (a === "--append") {
      opts.append = true;
      continue;
    }
    if (a === "--mode") {
      const v = argv[++i];
      if (v !== "observe" && v !== "enforce") {
        process.stderr.write(`--mode must be observe|enforce (got ${v})\n`);
        process.exit(2);
      }
      opts.mode = v;
      continue;
    }
    if (a.startsWith("-")) {
      process.stderr.write(`unknown flag: ${a}\n${HELP}`);
      process.exit(2);
    }
    opts.patterns.push(a);
  }
  if (opts.patterns.length === 0) {
    opts.patterns = ["src/**/*.{ts,tsx,js,jsx}"];
  }
  return opts;
}

function mergeContracts(
  existing: { E?: string; A?: string; desc?: string }[],
  fresh: { E: string }[],
): { E?: string; A?: string; desc?: string }[] {
  const seen = new Set(existing.map((c) => c.E).filter(Boolean));
  const out = [...existing];
  for (const c of fresh) {
    if (!seen.has(c.E)) {
      out.push(c);
      seen.add(c.E);
    }
  }
  return out;
}

export async function runScanCli(argv: string[]): Promise<void> {
  const opts = parseArgs(argv);
  const so = await runAstScan(opts.patterns);
  if (so.diagnostics.length) {
    for (const d of so.diagnostics) {
      process.stderr.write(`[${d.level}] ${d.filepath}:${d.line}  ${d.message}\n`);
    }
  }
  const toolNames = so.tools.map((t) => t.function.name);

  let payload: Record<string, unknown>;
  if (opts.append && opts.out !== "-" && existsSync(resolve(opts.out))) {
    const existing = yaml.load(readFileSync(resolve(opts.out), "utf-8")) as Record<string, unknown>;
    const fresh = suggestDetNlContracts(toolNames);
    const agents = (existing.agents as Record<string, { contracts?: { E?: string; A?: string; desc?: string }[] }>) ?? {};
    const block = agents[opts.agent] ?? { contracts: [] };
    block.contracts = mergeContracts(block.contracts ?? [], fresh);
    agents[opts.agent] = block;
    existing.agents = agents;
    existing.tools = so.tools;
    payload = existing;
  } else {
    payload = buildFallbackPayload(toolNames, { tools: so.tools }, opts.agent, opts.mode);
  }

  const header =
    "# Generated by: sponsio scan\n" +
    `# Scanned ${so.tools.length} tool(s) across ${opts.patterns.length} pattern(s).\n` +
    "# Review each contract before flipping to enforce.\n\n";
  const text = header + yaml.dump(payload, { lineWidth: 100 });

  if (opts.out === "-") {
    process.stdout.write(text);
    return;
  }
  const outPath = resolve(opts.out);
  writeFileSync(outPath, text, "utf-8");
  process.stdout.write(
    `✓ wrote ${outPath}\n` +
      `  tools:      ${so.tools.length}\n` +
      `  contracts:  ${((payload.agents as Record<string, { contracts?: unknown[] }>)?.[opts.agent]?.contracts ?? []).length}\n` +
      `  mode:       ${(payload.runtime as { mode?: string })?.mode ?? "observe"}\n`,
  );
}
