"""Renderers for :class:`~sponsio.reporting.Report`.

Three output formats:

* ``markdown`` — for Slack, GitHub issues, PR comments.
* ``html`` — for dashboards, email, or embedding in a ``<details>`` block.
* ``json`` — for machine consumption (CI, scripts, downstream tools).

All three are pure string-producing functions with no external
dependencies.  Zero Jinja — keeps the ``sponsio/`` core zero-dep
invariant intact.
"""

from __future__ import annotations

import html as _html
import json
from dataclasses import asdict
from datetime import datetime, timezone

from sponsio.reporting.aggregator import ContractStat, Report


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------


def render(report: Report, fmt: str = "markdown") -> str:
    """Render ``report`` in the requested format.

    Args:
        report: The aggregated report.
        fmt: One of ``"markdown"`` / ``"md"``, ``"html"``, ``"json"``.

    Raises:
        ValueError: On unknown format.
    """
    fmt = fmt.lower()
    if fmt in ("markdown", "md"):
        return render_markdown(report)
    if fmt == "html":
        return render_html(report)
    if fmt == "json":
        return render_json(report)
    raise ValueError(f"Unknown --format: {fmt!r}. Choose markdown, html, or json.")


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _ts_utc(ts: float) -> str:
    """Format unix seconds as ``YYYY-MM-DD HH:MM UTC`` (empty on 0)."""
    if ts <= 0:
        return "—"
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _agent_title(report: Report) -> str:
    if not report.agents:
        return "—"
    if len(report.agents) == 1:
        return report.agents[0]
    return f"{len(report.agents)} agents"


def _severity(c: ContractStat) -> str:
    """Heuristic one-glyph severity for a contract row."""
    if c.blocked:
        return "🛑 blocked"
    if c.observed:
        return "👁 observed"
    if c.retrying:
        return "🔁 retry"
    return "—"


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def render_markdown(report: Report) -> str:
    """Render a Slack-friendly Markdown report."""
    lines: list[str] = []
    title_agent = _agent_title(report)
    lines.append(f"# Sponsio Report — {title_agent}")
    lines.append("")
    lines.append(
        f"**Window:** {_ts_utc(report.window_start)} → {_ts_utc(report.window_end)}"
    )
    lines.append(f"**Sessions:** {report.total_sessions}")
    lines.append(f"**Events evaluated:** {report.total_events}")
    lines.append(f"**Violations caught:** {report.violations}")
    lines.append(f"**Actually blocked (enforce mode):** {report.blocked}")
    lines.append(f"**Would-have-blocked (observe mode):** {report.observed}")
    lines.append(f"**Sto retries:** {report.retrying}")
    lines.append(f"**Pass rate:** {report.pass_rate * 100:.1f}%")
    lines.append("")

    # Top violations table
    if report.by_contract:
        lines.append("## Top Violations")
        lines.append("")
        lines.append("| Contract | Pipeline | Violations | Severity | First seen |")
        lines.append("|---|---|---:|---|---|")
        for c in report.by_contract[:20]:
            contract_text = c.constraint.replace("|", "\\|")
            lines.append(
                f"| {contract_text} | {c.pipeline} | {c.violations} | "
                f"{_severity(c)} | {_ts_utc(c.first_seen)} |"
            )
        if len(report.by_contract) > 20:
            lines.append(f"| _…{len(report.by_contract) - 20} more_ | | | | |")
        lines.append("")

    # Most-violating sessions
    worst = [s for s in report.by_session if s.violations > 0][:5]
    if worst:
        lines.append("## Most-Violating Sessions")
        lines.append("")
        lines.append("| Session | Agent | Events | Violations |")
        lines.append("|---|---|---:|---:|")
        for s in worst:
            lines.append(
                f"| `{s.source}` | {s.agent_id} | {s.events} | {s.violations} |"
            )
        lines.append("")

    # What to do next
    lines.append("## What to do next")
    lines.append("")
    recs = _recommendations(report)
    for r in recs:
        lines.append(f"- {r}")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by `sponsio report` — see `sponsio report --help`.*")
    return "\n".join(lines) + "\n"


def _recommendations(report: Report) -> list[str]:
    """Heuristic "what to do" bullets.  Must never be empty."""
    recs: list[str] = []
    if report.total_events == 0:
        return [
            "No shadow-mode events yet. Start your agent with "
            '`sponsio.Sponsio(..., mode="observe")` and run some traffic, '
            "then re-run `sponsio report`."
        ]
    if report.observed > 0:
        recs.append(
            f"🕶 **{report.observed} events would have been blocked** in "
            "enforce mode. Flip `SPONSIO_MODE=enforce` once you're "
            "comfortable with the catch rate."
        )
    if report.blocked > 0:
        recs.append(
            f"🛑 **{report.blocked} events blocked in production.** Review "
            "the top contracts below and tune the ones with high block "
            "counts — they may be too strict, or pointing at a real bug."
        )
    if report.retrying > 0:
        recs.append(
            f"🔁 **{report.retrying} sto retries.** The agent self-corrected, "
            "but persistent retries on the same contract are worth a look."
        )
    # Top contract advice
    if report.by_contract:
        top = report.by_contract[0]
        recs.append(
            f"⚠ Top offender: **{top.constraint}** ({top.violations} violations "
            f"across {top.pipeline} pipeline). Investigate first."
        )
    if report.pass_rate >= 0.99 and report.violations == 0:
        recs.append("✅ No violations in this window. Nothing to do.")
    return recs


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


_HTML_STYLE = """
<style>
  .sponsio-report { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
      Helvetica, Arial, sans-serif; color: #1f2328; max-width: 860px; }
  .sponsio-report h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .sponsio-report .meta { color: #656d76; font-size: 0.9rem; margin-bottom: 1rem; }
  .sponsio-report table { border-collapse: collapse; width: 100%; margin: 0.5rem 0 1.25rem 0; }
  .sponsio-report th, .sponsio-report td { border: 1px solid #d0d7de;
      padding: 0.4rem 0.6rem; font-size: 0.9rem; text-align: left; }
  .sponsio-report th { background: #f6f8fa; }
  .sponsio-report .num { text-align: right; font-variant-numeric: tabular-nums; }
  .sponsio-report .pill { display: inline-block; padding: 0.1rem 0.45rem;
      border-radius: 0.75rem; font-size: 0.8rem; }
  .sponsio-report .pill-blocked { background: #ffebe9; color: #cf222e; }
  .sponsio-report .pill-observed { background: #fff8c5; color: #9a6700; }
  .sponsio-report .pill-retry { background: #ddf4ff; color: #0969da; }
</style>
""".strip()


def _pill_for(c: ContractStat) -> str:
    if c.blocked:
        return '<span class="pill pill-blocked">blocked</span>'
    if c.observed:
        return '<span class="pill pill-observed">observed</span>'
    if c.retrying:
        return '<span class="pill pill-retry">retry</span>'
    return "—"


def render_html(report: Report) -> str:
    """Render a self-contained HTML report (single ``<div>``, inline CSS)."""
    esc = _html.escape
    title_agent = esc(_agent_title(report))
    parts = [_HTML_STYLE, '<div class="sponsio-report">']
    parts.append(f"<h1>Sponsio Report — {title_agent}</h1>")
    parts.append(
        f'<div class="meta">Window: {esc(_ts_utc(report.window_start))} '
        f"→ {esc(_ts_utc(report.window_end))} &middot; "
        f"{report.total_sessions} sessions &middot; "
        f"{report.total_events} events &middot; "
        f"pass rate {report.pass_rate * 100:.1f}%</div>"
    )
    parts.append("<table>")
    parts.append(
        "<tr><th>Blocked</th><th>Observed</th><th>Sto retries</th>"
        "<th>Violations total</th></tr>"
    )
    parts.append(
        f'<tr><td class="num">{report.blocked}</td>'
        f'<td class="num">{report.observed}</td>'
        f'<td class="num">{report.retrying}</td>'
        f'<td class="num">{report.violations}</td></tr>'
    )
    parts.append("</table>")

    if report.by_contract:
        parts.append("<h2>Top violations</h2>")
        parts.append("<table>")
        parts.append(
            "<tr><th>Contract</th><th>Pipeline</th><th>Violations</th>"
            "<th>Severity</th><th>First seen</th></tr>"
        )
        for c in report.by_contract[:20]:
            parts.append(
                "<tr>"
                f"<td>{esc(c.constraint)}</td>"
                f"<td>{esc(c.pipeline)}</td>"
                f'<td class="num">{c.violations}</td>'
                f"<td>{_pill_for(c)}</td>"
                f"<td>{esc(_ts_utc(c.first_seen))}</td>"
                "</tr>"
            )
        parts.append("</table>")

    worst = [s for s in report.by_session if s.violations > 0][:5]
    if worst:
        parts.append("<h2>Most-violating sessions</h2>")
        parts.append("<table>")
        parts.append(
            "<tr><th>Session</th><th>Agent</th><th>Events</th><th>Violations</th></tr>"
        )
        for s in worst:
            parts.append(
                "<tr>"
                f"<td><code>{esc(s.source)}</code></td>"
                f"<td>{esc(s.agent_id)}</td>"
                f'<td class="num">{s.events}</td>'
                f'<td class="num">{s.violations}</td>'
                "</tr>"
            )
        parts.append("</table>")

    parts.append("</div>")
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------


def render_json(report: Report) -> str:
    """Render the report as pretty-printed JSON (machine-readable)."""
    payload = {
        "agents": report.agents,
        "window": {
            "start": report.window_start,
            "end": report.window_end,
            "start_iso": _ts_utc(report.window_start),
            "end_iso": _ts_utc(report.window_end),
        },
        "totals": {
            "events": report.total_events,
            "sessions": report.total_sessions,
            "passed": report.passed,
            "blocked": report.blocked,
            "observed": report.observed,
            "retrying": report.retrying,
            "violations": report.violations,
            "pass_rate": report.pass_rate,
        },
        "by_contract": [asdict(c) for c in report.by_contract],
        "by_session": [asdict(s) for s in report.by_session],
    }
    return json.dumps(payload, indent=2, default=str) + "\n"
